### PR TITLE
feat(*): use resty-luasocket to replace socket & http hacks

### PR DESCRIPTION
**Pull request by windmgc**
So that `lua-resty-gcp` no longer requires `lua-resty-aws`

KAG-656
https://github.com/Kong/lua-resty-gcp/issues/10

### CODE REVIEW

**Comment by windmgc** [comment]
@StarlightIbuki Could you please help review and test this? Thanks!

**Comment by StarlightIbuki** [comment]
This lib does not have a complete set of tests. Please make a build and test it with at least `kong.vault` and config backup.

**Comment by Tieske** [comment]
There's a number `ssl_verify = false`, like this one; https://github.com/Kong/lua-resty-gcp/blob/82e9f242640f5fe96eed5065be32f0a534efbbf3/src/resty/gcp/init.lua#L74 in the code. They should be updated as well.

The reason to switch to `lua-resty-luasocket` was mainly to be able to use `ssl_verify = true`. But that will immediately have the requirement to also update Kong to set up the ssl settings for `lua-resty-luasocket` which it currently doesn't do yet afaik.

These setting has been enabled in `lua-resty-aws` and `lua-resty-azure` (by @tysoekong ), these are waiting for Kong to implement those settings, so those versions can be bumped as well.

See https://konghq.atlassian.net/browse/KAG-656

**Comment by windmgc** [comment]
I'm working on it but I cannot get AWS version bumped because gcp already pins it to 1.1.2...

**Comment by Tieske** [comment]
> I'm working on it but I cannot get AWS version bumped because gcp already pins it to 1.1.2...

Ah, yes, now I see. Good work! 👍

**Comment by windmgc** [comment]
Tested locally with GCP clustering backup sync, I don't have any special config so it seems work well with default cert chain:

Exporting:
```
2023/04/18 21:52:39 [info] 95293#0: *12 [lua] init.lua:124: [fallback config] exporting config to fallback storage, context: ngx.timer
2023/04/18 21:52:40 [info] 95293#0: *12 [lua] init.lua:128: [fallback config] successfully exported config to fallback storage, context: ngx.timer
```
image

Importing(and succeed in serving proxy request after that):
```
2023/04/18 22:48:38 [info] 9074#0: *12 [lua] init.lua:251: fallback_config_import(): [fallback config] control_plane not connected. Fetching config from fallback storage, context: ngx.timer
2023/04/18 22:48:40 [debug] 9074#0: *12 [lua] init.lua:208: [fallback config] successfully applied config from fallback storage
2023/04/18 22:48:40 [info] 9074#0: *12 [lua] init.lua:256: fallback_config_import(): [fallback config] fallback config applied, context: ngx.timer
```

**Comment by windmgc** [comment]
Succeed verifying in kong vault functions(with a little tweak on kong's side, will post a PR later.)
This also needs https://github.com/Tieske/lua-resty-luasocket/pull/3 merged to get it to work.

@StarlightIbuki If the major version of lua-resty-luasocket still remains the same, please feel free to merge this one and bump a version.

**Comment by Tieske** [comment]
`lua-resty-luasocket` version `1.1.1` was just released with the SNI fix

**Review by StarlightIbuki — APPROVED** [review]
The code looks much cleaner without details of HTTP and cosocket. Just worry if it still works with non-SSL.

**Comment by windmgc** [comment]
@StarlightIbuki It has no influence on HTTP-only request because the `ssl_verify` will be ignored by `lua-resty-http`.

The only thing we need to take care of is those third-party HTTPs API using self-signed certs

**Pull request merged**
